### ISSUE TITLE
Errors after cloning

### ISSUE THREAD

**Issue by ccorcos** [jhabdas/react-native-webpack-starter-kit#54]
I npm installed, then:

```
~/C/r/treasure ❯❯❯ npm start                                             master

> Treasure@0.1.0 start /Users/chet/Code/react-native/treasure
> rnws start

Server listening at http://localhost:8080
Webpack dev server listening at  http://localhost:8082
Hash: 063de06d8e9259b0ac10
Version: webpack 1.12.14
Time: 1368ms
               Asset     Size  Chunks             Chunk Names
    index.android.js    24 kB       0  [emitted]  index.android
        index.ios.js  24.1 kB       1  [emitted]  index.ios
index.android.js.map  35.1 kB       0  [emitted]  index.android
    index.ios.js.map  36.5 kB       1  [emitted]  index.ios
chunk    {0} index.android.js, index.android.js.map (index.android) 17 kB [rendered]
chunk    {1} index.ios.js, index.ios.js.map (index.ios) 17 kB [rendered]

ERROR in ./src/main.android.js

/Users/chet/Code/react-native/treasure/src/main.android.js
  5:1  warning  Rule 'no-empty-class' was removed and replaced by: no-empty-character-class  no-empty-class
  5:1  warning  Rule 'no-empty-label' was removed and replaced by: no-labels                 no-empty-label
  5:1  error    Rule 'global-strict' was removed and replaced by: strict                     global-strict
  5:1  warning  Rule 'no-extra-strict' was removed and replaced by: strict                   no-extra-strict
  5:1  warning  Rule 'no-space-before-semi' was removed and replaced by: semi-spacing        no-space-before-semi
  5:1  warning  Rule 'no-wrap-func' was removed and replaced by: no-extra-parens             no-wrap-func
  5:1  warning  Rule 'space-after-keywords' was removed and replaced by: keyword-spacing     space-after-keywords
  5:1  warning  Rule 'space-return-throw-case' was removed and replaced by: keyword-spacing  space-return-throw-case
  5:1  warning  Rule 'space-unary-word-ops' was removed and replaced by: space-unary-ops     space-unary-word-ops

✖ 9 problems (1 error, 8 warnings)


ERROR in ./src/main.ios.js

/Users/chet/Code/react-native/treasure/src/main.ios.js
  5:1  warning  Rule 'no-empty-class' was removed and replaced by: no-empty-character-class  no-empty-class
  5:1  warning  Rule 'no-empty-label' was removed and replaced by: no-labels                 no-empty-label
  5:1  error    Rule 'global-strict' was removed and replaced by: strict                     global-strict
  5:1  warning  Rule 'no-extra-strict' was removed and replaced by: strict                   no-extra-strict
  5:1  warning  Rule 'no-space-before-semi' was removed and replaced by: semi-spacing        no-space-before-semi
  5:1  warning  Rule 'no-wrap-func' was removed and replaced by: no-extra-parens             no-wrap-func
  5:1  warning  Rule 'space-after-keywords' was removed and replaced by: keyword-spacing     space-after-keywords
  5:1  warning  Rule 'space-return-throw-case' was removed and replaced by: keyword-spacing  space-return-throw-case
  5:1  warning  Rule 'space-unary-word-ops' was removed and replaced by: space-unary-ops     space-unary-word-ops

✖ 9 problems (1 error, 8 warnings)


ERROR in ./src/components/App.js

/Users/chet/Code/react-native/treasure/src/components/App.js
  5:1  warning  Rule 'no-empty-class' was removed and replaced by: no-empty-character-class  no-empty-class
  5:1  warning  Rule 'no-empty-label' was removed and replaced by: no-labels                 no-empty-label
  5:1  error    Rule 'global-strict' was removed and replaced by: strict                     global-strict
  5:1  warning  Rule 'no-extra-strict' was removed and replaced by: strict                   no-extra-strict
  5:1  warning  Rule 'no-space-before-semi' was removed and replaced by: semi-spacing        no-space-before-semi
  5:1  warning  Rule 'no-wrap-func' was removed and replaced by: no-extra-parens             no-wrap-func
  5:1  warning  Rule 'space-after-keywords' was removed and replaced by: keyword-spacing     space-after-keywords
  5:1  warning  Rule 'space-return-throw-case' was removed and replaced by: keyword-spacing  space-return-throw-case
  5:1  warning  Rule 'space-unary-word-ops' was removed and replaced by: space-unary-ops     space-unary-word-ops

✖ 9 problems (1 error, 8 warnings)

webpack: bundle is now VALID.
 ┌────────────────────────────────────────────────────────────────────────────┐
 │  Running packager on port 8081.                                            │
 │                                                                            │
 │  Keep this packager running while developing on any JS projects. Feel      │
 │  free to close this tab and run your own packager instance if you          │
 │  prefer.                                                                   │
 │                                                                            │
 │  https://github.com/facebook/react-native                                  │
 │                                                                            │
 └────────────────────────────────────────────────────────────────────────────┘
Looking for JS files in
   /Users/chet/Code/react-native/treasure
   /Users/chet/Code/react-native/treasure/node_modules/react-native-webpack-server/_entry

[10:11:43 PM] <START> Building Dependency Graph
[10:11:43 PM] <START> Crawling File System
[10:11:43 PM] <START> Loading bundles layout
[10:11:43 PM] <END>   Loading bundles layout (1ms)
[Hot Module Replacement] Server listening on /hot

React packager ready.

react-native packager ready...
Failed to build DependencyGraph: Cannot read property 'root' of null
TypeError: Cannot read property 'root' of null
    at index.js:16:60
    at tryCallOne (/Users/chet/Code/react-native/treasure/node_modules/promise/lib/core.js:37:12)
    at /Users/chet/Code/react-native/treasure/node_modules/promise/lib/core.js:123:15
    at flush (/Users/chet/Code/react-native/treasure/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)

```

**Comment by jhabdas** [comment]
Thanks for reporting your issue @ccorcos. It's unexpected you'd see linting errors during fresh install of this project. In fact, I can see from the build output here the linter is complaining about rules which do not exist in this project's `.eslintrc` file.

What happens if you clone this repo again fresh, reinstall dependencies and start the app?

**Comment by jhabdas** [comment]
@ccorcos any updates?

**Comment by jhabdas** [comment]
@ccorcos I've updated the installation instructions in the `README` to provide some additional info and an a virtual environment configured to run this app with Docker. If you continue to experience environment issues feel free to give the Docker approach a try. But if you're on OS X you shouldn't need to. Good luck!

**Comment by ccorcos** [comment]
Sounds good -- havent had the free time again to dive into RN :'( I'll keep you posted though. Maybe in a week

**Comment by ccorcos** [comment]
worked!

**Comment by jhabdas** [comment]
Awesome!  It should support the capability of syncing files between systems, but I wasn't able to try that out yet
