### ISSUE TITLE
Android crash on fresh install 

### ISSUE THREAD

**Issue by ochervak** [jhabdas/react-native-webpack-starter-kit#58]
Steps:
- Clone repo
- npm i
- run Android Studio under Nexus 5X and 6.0 Marshmallow

Result: 
Crash

![5554 nexus_5x_api_23 2016-02-29 16-55-02](https://cloud.githubusercontent.com/assets/13982649/13398110/8b9d5f92-df05-11e5-8170-90d674ad4b6d.png)

**Comment by ochervak** [comment]
Additional stacktrace from studio:
```
02-29 16:58:30.445 3330-4222/com.app E/ReactNativeJS: Module AppRegistry is not a registered callable module.
02-29 16:58:30.459 3330-4223/com.app E/unknown:React: Exception in native call from JS
                                                      com.facebook.react.bridge.NativeArgumentsParseException: RKSourceCode.getScriptText got 0 arguments, expected 2
                                                          at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:227)
                                                          at com.facebook.react.bridge.NativeModuleRegistry$ModuleDefinition.call(NativeModuleRegistry.java:158)
                                                          at com.facebook.react.bridge.NativeModuleRegistry.call(NativeModuleRegistry.java:58)
                                                          at com.facebook.react.bridge.CatalystInstanceImpl$NativeModulesReactCallback.call(CatalystInstanceImpl.java:431)
                                                          at com.facebook.react.bridge.queue.NativeRunnableDeprecated.run(Native Method)
                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                          at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                          at android.os.Looper.loop(Looper.java:148)
                                                          at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:185)
                                                          at java.lang.Thread.run(Thread.java:818)
02-29 16:58:30.461 3330-4222/com.app I/ReactNativeJS: 'Failed to print error: ', 'undefined is not an object (evaluating \'RCTSourceCode.getScriptText().\nthen\')'
```

**Comment by jhabdas** [comment]
Thanks for the report. I'll look into this when I have a chance. Meanwhile you may also want to try requesting help in the Gitter channel (link from README badge). /cc @niftylettuce for familiarity with Android RN dev

**Comment by shprink** [comment]
http://stackoverflow.com/questions/34969858/react-native-module-appregistry-is-not-a-registered-callable-module/35630058

Please let us know if you find a solution!

thanks

**Comment by ochervak** [comment]
will do!
i try clean install from React Native official docs, and it works well...

**Comment by jhabdas** [comment]
I'll regenerate the RN app from init this weekend. It requires some hacks to chop off some of the tooling they're building for iOS so I'll look for a happy middle ground.

**Comment by gustavovnicius** [comment]
+1

**Comment by jhabdas** [comment]
Sorry for the flub all. I'll be sure this gets fixed as soon as I can. Meanwhile, try a "react-native" upgrade after installing and see if you can push through any issues. I will get on this Saturday.

**Comment by gustavovnicius** [comment]
It was my first try (updating react-native after cloning the repo), and it gives the same error. Not tried this: [http://stackoverflow.com/a/35630058]. If I discover anything new I'll report here.

**Comment by jhabdas** [comment]
While this is being addressed, please try testing on an actual device and being sure you look through the closed Android issues in this repo. Also, and feedback on the Android instructions in the README is welcome and relevant here.

**Comment by shprink** [comment]
BTW @vjeux has never heard of this error before :(

https://twitter.com/julienrenaux/status/704556052902191104

**Comment by jhabdas** [comment]
@ochervak @shprink to better understand how to debug this I need to try and replicate your environments as closely as possible. If possible, please provide your kit version used and your current `node -v && npm -v`. Thanks!

**Comment by jhabdas** [comment]
Released [a new version](https://github.com/jhabdas/react-native-webpack-starter-kit/releases/tag/v2.21.0) of the starter kit on the latest RN stable ([`v0.21.0`](https://github.com/facebook/react-native/releases/tag/v0.21.0)), which includes a host of Android goodies. Not sure if it's going to resolve this issue, but it's what I'll be using try try and replicate this issue with what information I have.

**Comment by gustavovnicius** [comment]
Same thing after updating the starter kit (already cleaned the node_modules dir). Tried reinstall node (v5.7.1) and all packages again too :disappointed: 
On a fresh react-native it works pretty well =/

**Comment by niftylettuce** [comment]
Hey guys, from my experience, I went straight with the bundler that RN provides.  Webpack is a nightmare to work with when you want to do anything complex.  The package system is not the best in my opinion, and the amount of time you will save using the built-in packager/bundling system is wayyyy less compared to the time you'll spend trying to configure your `webpack.config.js` files.

**Comment by jhabdas** [comment]
@gustavovnicius could you provide your Node, NPM and emulator version. Did you try the port forwarding run script,

**Comment by jhabdas** [comment]
Thanks for the knowledge drop @niftylettuce. What kind of environment are you using? My goal is to keep things simple while helping others move forward with a simple extensible toolset.

**Comment by gustavovnicius** [comment]
Sure!
node v5.7.1, npm 3.6.0 running on latest genymotion 2.6.0 / vbox 5.0.16.
After the update, running in an actual device (Android 5.0) it gives a slightly different error 
![screenshot_2016-03-06-22-29-39](https://cloud.githubusercontent.com/assets/2379486/13558890/12e4f840-e3eb-11e5-9404-b83c1e88f396.jpg)

But after reloading JS, it works

**Comment by niftylettuce** [comment]
@jhabdas I'm using RN v0.20 and just running `npm start` when I want to run my project.  I really don't need webpack.  With the latest version of RN, you can have custom `.babelrc` files, which the packager respects.  In older versions, you can just edit the `.babelrc` file directly in the `./node_modules/react-native` folder that the `packager.sh` script uses.  Here's what my `.babelrc` file looks like:

```.babelrc
{
  "presets": [ "react-native", "stage-0" ],
  "plugins": [
    "transform-decorators-legacy"
  ]
}
```

**Comment by niftylettuce** [comment]
My `npm start` command looks like this in `package.json`:

```json
"start": "node_modules/react-native/packager/packager.sh",
```

**Comment by jhabdas** [comment]
After reloading JS, it works? Could you expand. While the default packager may seem easier I have my doubts as to its long-term efficacy while building and maintaining apps. As suggested, the goal here is to keep tooling light, and Id rather not see RN turned into a framework.

**Comment by niftylettuce** [comment]
@jhabdas Yeah, Reload JS works fine for me.  The moment I switched out of all this webpack nonsense my workflow became SO much easier. I was spending 90% of the time before configuring webpack, now I don't have to configure anything, I can focus on the code and RN packages themselves, writing decorators, etc.  My key tip for ANYONE using RN is to use RN packager directly, and `.babelrc` for any cool Babel plugins you need.

**Comment by jhabdas** [comment]
Thanks, @niftylsttuce. As a result, what changes do you feel this kit could make to best serve Android builders while continuing to provide extensible support for building apps?

**Comment by jhabdas** [comment]
I have my doubts about using Babel given its immaturity. But thanks for the info.

**Comment by niftylettuce** [comment]
My setup is like this:

```log
index.android.js
index.ios.js
src/
package.json
```

Inside my `index.android.js` and `index.ios.js` files is the following code:

```js
require('./src');
```

And finally inside `./src` dir, is a file `index.js`, which is completely written in ES6/7 (I have `stage-0` flag enabled in `.babelrc` (see above)).  The RN packager picks this up all relatively easily, and my app runs just fine.  Source maps work too.

I feel like this kit should be deprecated and nobody should use webpack anymore for RN development.  I literally spent hours trying to configure it, get it working, used it for months, just to run into the same problems over and over again with webpack.  Webpack is unstable and I dislike it (I'm speaking from hours of REALLY intense bugs, debugging, and configurations, not just saying this to put hate on anyone's projects or packages).  If I were maintaining this, I'd put a DEPRECATED notice on the Readme.md and disable Issues here on the settings of the repo.  It's just way too messy to try to use RN with Webpack.  Maybe React and Webpack are fine, but with RN you have to worry about all the RN packages that the packager picks up, all the `ignore` files and package names, image assets, etc.

If you had doubts about Babel, it's what RN itself is using and it's stable for development IMO (at least 100x more than Webpack).  True, it breaks sometimes, but only because they are moving so fast and are at least somewhat more organized :laughing:.

**Comment by gustavovnicius** [comment]
@jhabdas It works aftter reloading, but after some changes, eventually it gives the same error again, couldn't realize why.

After some readings:
[RN JS Env](https://facebook.github.io/react-native/docs/javascript-environment.html#javascript-syntax-transformers), @niftylettuce feedback, and by looking at [RNWS](https://github.com/mjohnston/react-native-webpack-server#looking-for-a-maintainer) which is "not actively maintained", wouldn't be better / simpler if the starter kit relies on RN packager, with changes needed made on `.babelrc` ? After all, the RN itself relies on babel.

**Comment by niftylettuce** [comment]
Android works fine out of the box with the packager.  No problems there.  I add this to my `package.json` and run it whenever I'm running on a device plugged in over `adb`...

```json
"adb-reverse": "adb reverse tcp:8080 tcp:8080 && adb reverse tcp:8081 tcp:8081",
```

Then run it with `npm run adb-reverse`.

**Comment by jhabdas** [comment]
Stage 0 seems like a bad idea to me as its too edge to build maintainable apps with. But, again, thanks for the info. There are a lot of ways to build, and it'd be great to learn from what others are doing.

**Comment by niftylettuce** [comment]
Oh!  Another thing that makes life easier for Android/iOS reloading etc - is my package "Frappe".

Check it out at <https://github.com/niftylettuce/frappe>.

![frappe](https://camo.githubusercontent.com/0f5290f9fbf6fbc75ca3bff7d4b2f368296212f2/68747470733a2f2f63646e2e7261776769742e636f6d2f6e696674796c6574747563652f6672617070652f6d61737465722f6d656469612f64656d6f2e706e67)

**Comment by jhabdas** [comment]
I spent time working through RN Android setup this weekend. I'm still working on it. I feel it's important to build maintainable and extensible apps. If you're interested in a quick win all have a choice on how to build. But I do not feel using the methods provided using the default RN JS language extensions is the best way to build apps either for iOS or Android.

**Comment by yves-s** [comment]
+1

**Comment by jhabdas** [comment]
I'll put an hour on this today for the +1. If the example app in the RNWS repo isn't experiencing the same issue the problem shouldn't be too hard to isolate. Thanks for the nudge.

**Comment by jhabdas** [comment]
Got sidetracked publishing a new blog post and I'm still stuck getting emulators functioning in the IDE.

Could someone try one of the Example RN apps in react-native-webpack-server repo and let me know if your emulator fires up without issue there?

**Comment by stickperson** [comment]
Just ran the BabelES6 example in that repo and got the following screen:

![error](http://i.imgur.com/CeeEk9o.png)

**Comment by jhabdas** [comment]
Thanks for checking. Next step would to to look back at older Releases of
this kit to see if there's a possible conflict with newer RN tooling. iOS
requires some modifications. And it seems Android will as well following
the latest fresh init in 2.21.

**Comment by jhabdas** [comment]
Greenkeeper just submitted https://github.com/jhabdas/react-native-webpack-starter-kit/pull/72 for RN the latest `0.22` patch, which gives a different backtrace:

```
03-21 21:59:35.420 2570-2570/com.app E/unknown:React: Exception in native call from JS
                                                      java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: ReferenceError: Can't find variable: __fbBatchedBridge (<unknown file>:1)
                                                          at com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:171)
                                                          at com.facebook.react.ReactInstanceManagerImpl.createReactContext(ReactInstanceManagerImpl.java:879)
                                                          at com.facebook.react.ReactInstanceManagerImpl.access$700(ReactInstanceManagerImpl.java:104)
                                                          at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(ReactInstanceManagerImpl.java:200)
                                                          at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(ReactInstanceManagerImpl.java:183)
                                                          at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                          at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                          at java.lang.Thread.run(Thread.java:818)
                                                       Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: ReferenceError: Can't find variable: __fbBatchedBridge (<unknown file>:1)
                                                          at com.facebook.react.common.futures.SimpleSettableFuture.get(SimpleSettableFuture.java:68)
                                                          at com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:147)
                                                          at com.facebook.react.ReactInstanceManagerImpl.createReactContext(ReactInstanceManagerImpl.java:879) 
                                                          at com.facebook.react.ReactInstanceManagerImpl.access$700(ReactInstanceManagerImpl.java:104) 
                                                          at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(ReactInstanceManagerImpl.java:200) 
                                                          at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(ReactInstanceManagerImpl.java:183) 
                                                          at android.os.AsyncTask$2.call(AsyncTask.java:295) 
                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                          at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                          at java.lang.Thread.run(Thread.java:818) 
                                                       Caused by: java.lang.RuntimeException: ReferenceError: Can't find variable: __fbBatchedBridge (<unknown file>:1)
                                                          at com.facebook.react.bridge.ReactBridge.loadScriptFromAssets(Native Method)
                                                          at com.facebook.react.bridge.JSBundleLoader$1.loadScript(JSBundleLoader.java:32)
                                                          at com.facebook.react.bridge.CatalystInstanceImpl$2.call(CatalystInstanceImpl.java:157)
                                                          at com.facebook.react.bridge.CatalystInstanceImpl$2.call(CatalystInstanceImpl.java:148)
                                                          at com.facebook.react.bridge.queue.MessageQueueThreadImpl$1.run(MessageQueueThreadImpl.java:73)
                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                          at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                          at android.os.Looper.loop(Looper.java:148)
                                                          at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:187)
                                                          at java.lang.Thread.run(Thread.java:818) 
03-21 21:59:35.470 2570-2587/com.app W/EGL_emulation: eglSurfaceAttrib not implemented
```

After visiting the release history for this kit the error encountered upon Android simulation varies by version. I believe users have been working around the problems by using [adb and running directly devices](https://github.com/jhabdas/react-native-webpack-starter-kit#android). What have your experiences been?

**Comment by yves-s** [comment]
I just tried to run an example of the react-native repo and it did work. After I got that running I again tried it with the starter kit but still the same error. I'm not sure if that helps. I'm further no it, if I have something else I will let you know.

**Comment by Nickman87** [comment]
I am experiencing the same "Module AppRegistry is not a registered callable module" error when running inside an emulator.
I did also make the android bundle by running webpack with the given config and it works perfectly on react-native-playground. The build seems to be working fine so it's not in the javascript code. The issue seems to be in the setup of reactnative?

Maybe in the react-native-webpack-server or something?

**Comment by ssomnoremac** [comment]
Wanted to chime in that I have been getting the "AppRegistry" error mentioned in this thread on a separate Android RN project after upgrading from RN 19.0 to 23.1. Suggest this is perhaps a RN issue and we might want to post on the main RN issues thread. We'll need some +1's.

**Comment by ferologics** [comment]
Same thing for me... Completely agree with @niftylettuce, I'd deprecate this project. (sent you an email @niftylettuce)

**Comment by jhabdas** [comment]
@ferologics I've never heard of a starter kit being deprecated due to a bug. Am I missing something?

**Comment by jhabdas** [comment]
@ferologics I don't have any intention of deprecating project due to a bug running Android in a simulator. This project was extracted from the [Lumpen Radio](git@github.com:jhabdas/lumpen-radio.git
https://github.com/jhabdas/lumpen-radio) benefit project after delivering the iOS app to the App Store. At that time RN Android was just emerging into the RN ecosystem and, as suggested in the project `README`, Android users will likely experience some bumpiness until proper support is added. Hence this issue.

**Comment by tjgillies** [comment]
I'm getting this error running on an actual device

**Comment by jhabdas** [comment]
Thanks noting that @tjgillies. Just to verify, you were trying to use adb via the NPM script in the package manifest to connect and are using the required version of Android specified in the README? I'd love to debug the Android error, but it feels like it's in a downstream dep and I'm not sure where to start.

**Comment by tjgillies** [comment]
I was trying to run over adb connected to wifi. When I used an actual usb cable it worked.

**Comment by cypherq** [comment]
Isn't this issue caused because of reversing `8081` to `8080` port?

**Comment by Smileo** [comment]
Hi @jhabdas Do you have any update about this? Thanks.

**Comment by jhabdas** [comment]
@smileo need to find someone with the time and inclination to debug why the android bundles generated won't load in the simulator but will on an actual device (and RNPlay, from feedback in the thread above).

**Comment by eetujalonen** [comment]
Getting the same "Module AppRegistry is not a registered callable module." when using a real Nexus 5X and running this projects example code.

**Comment by nevir** [comment]
One thing that might be related `AppRegistry.registerComponent` needs to be called when the bundle loads; if you defer it (async in any way), you get this error

**Comment by jhabdas** [comment]
@nevir Interesting. These bundles are generated async so perhaps that's the issue.

I spent a few hours debugging this today without any luck. But I _was_ able to develop Android with HMR using the RN CLI with `react-native run-android` after [tweaking `build.gradle`](http://stackoverflow.com/a/37360099/712334) to point to the `src/main.android.js` entry file. The whole Android Studio / Gradle experience I found to be a bit wonky. Hopefully developing RN apps for Android gets easier once [buck](https://github.com/facebook/buck) is better integrated into the RN ecosystem. Until then I'm going to lock conversation on this issue as there's not much more to be said here. If someone finds a fix please submit a PR this way. Happy coding!
