### ISSUE TITLE
Windows Use: watchman inotify-add-watch error

### ISSUE THREAD

**Issue by outdooricon** [jhabdas/react-native-webpack-starter-kit#66]
Thank you so much for your work on this, loving the Winodws support!! I've followed your updated docs with fresh clone and images and the addition to the watchman config. Here's waht I'm seeing now after npm start in the image:

```
react-native packager ready...
 ERROR  A non-recoverable condition has triggered.  Watchman needs your help!
The triggering condition was at timestamp=1457267029: inotify-add-watch(/app/node_modules/babel-preset-stage-1/node_modules/babel-plugin-transform-class-properties/node_modules/babel-runtime/core-js/reflect) -> The user limit on the total number of inotify watches was reached; increase the fs.inotify.max_user_watches sysctl
All requests will continue to fail with this message until you resolve
the underlying problem.  You will find more information on fixing this at
https://facebook.github.io/watchman/docs/troubleshooting.html#poison-inotify-add-watch

{"watchmanResponse":{"version":"4.5.0","error":"A non-recoverable condition has triggered.  Watchman needs your help!\nThe triggering condition was at timestamp=1457267029: inotify-add-watch(/app/node_modules/babel-preset-stage-1/node_modules/babel-plugin-transform-class-properties/node_modules/babel-runtime/core-js/reflect) -> The user limit on the total number of inotify watches was reached; increase the fs.inotify.max_user_watches sysctl\nAll requests will continue to fail with this message until you resolve\nthe underlying problem.  You will find more information on fixing this at\nhttps://facebook.github.io/watchman/docs/troubleshooting.html#poison-inotify-add-watch\n"}}
Error: A non-recoverable condition has triggered.  Watchman needs your help!
The triggering condition was at timestamp=1457267029: inotify-add-watch(/app/node_modules/babel-preset-stage-1/node_modules/babel-plugin-transform-class-properties/node_modules/babel-runtime/core-js/reflect) -> The user limit on the total number of inotify watches was reached; increase the fs.inotify.max_user_watches sysctl
All requests will continue to fail with this message until you resolve
the underlying problem.  You will find more information on fixing this at
https://facebook.github.io/watchman/docs/troubleshooting.html#poison-inotify-add-watch

    at BunserBuf.<anonymous> (/app/node_modules/react-native/node_modules/sane/node_modules/fb-watchman/index.js:95:23)
    at emitOne (events.js:77:13)
    at BunserBuf.emit (events.js:169:7)
    at BunserBuf.process (/app/node_modules/react-native/node_modules/bser/index.js:289:10)
    at /app/node_modules/react-native/node_modules/bser/index.js:244:12
    at nextTickCallbackWith0Args (node.js:415:9)
    at process._tickCallback (node.js:344:13)
```

**Comment by lucianlo** [comment]
@jhabdas 

## Bundling

Building the app for distribution.

1. Execute `npm run bundle` to generate the [offline JS bundle](https://facebook.github.io/react-native/docs/running-on-device-ios.html#using-offline-bundle).
1. For iOS, update `AppDelegate.m` to load from pre-bundled file on disk.
1. Test the application, create an archive and submit to the store.

when my app's js had bundled, update `AppDelegate.m` to local, there is something wrong with this.

saying that:

> **unable to execute js call: fbBatchedBridge is undefined**

then how can i test in my real iphone?thx

**Comment by jhabdas** [comment]
Looks like Windows users may have an option for RN dev in the future given the [recent announcement](https://blogs.windows.com/buildingapps/2016/04/13/react-native-on-the-universal-windows-platform/) Microsoft and Facebook will be collaborating on Universal Windows Platform (UWP) support for RN.
